### ISSUE TITLE
Why mingw32?

### ISSUE THREAD

**Issue by GLolol** [roblox-linux-wrapper/single-site-browser-vala#1]
As far as I'm concerned, there are two ways that ROBLOX can be started into a game.

1) Use the Web APIs + browser-less launching (this is used for Chrome because it doesn't support NPAPI plugins anymore).

2) Use the RobloxProxy.dll NPAPI plugin to load the game. 

Since we're using option 1) here, I don't see why the browser needs to be compiled via mingw32 as an .exe file. It would be much more stable as a native Linux application, and would still be able to call Wine processes accordingly.

**Comment by alfonsojon** [comment]
I would love to use the web API, but wine does not provide a way to register protocol URLs the way we can register file extensions, so there's not a clear way to forward the request to Roblox through wine. The solution I've implemented is a single site browser in Vala which can be compiled on Windows. This browser uses WebKit and should theoretically be fully compatible with wine, eliminating the issues we've been having with Firefox, as well as the need for a highly complex browser. Think of it as a replacement/successor to the "roblox-browser" project.

**Comment by alfonsojon** [comment]
Perhaps we could implement a stub which registers itself as a protocol handler, which can then parse the arguments given and launch RobloxPlayerBeta.exe with the appropriate flags?

**Comment by alfonsojon** [comment]
Ping @GLolol

**Comment by GLolol** [comment]
sgtm
